---
- name: AXELOR SETUP
  hosts: prod
  become: true
  remote_user: ubuntu
  vars_files:
          - vars/main.yml
  roles:
          - git
          - java
          - tomcat
          - postgresql
          - axelor
